spring.application.name=apex-wallet

# Use Postgres DB provided by docker-compose (start it with `docker-compose up -d`)
spring.datasource.url=jdbc:postgresql://localhost:5432/wallet_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA / Hibernate configuration (adjust as needed)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379
